# Generated by Django 4.2.1 on 2023-08-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SubscriptionDetail',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('part', models.CharField(max_length=45)),
                ('start_date', models.DateField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ingredient')),
            ],
            options={
                'db_table': 'SubscriptionService',
            },
        ),
    ]
