# Generated by Django 4.2.1 on 2023-08-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_alter_dog_created_at_alter_dog_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='is_checkd',
            new_name='is_checked',
        ),
    ]
