# Generated by Django 4.2.1 on 2023-08-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='배송 준비 중', max_length=45)),
            ],
            options={
                'db_table': 'Delivery',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=45)),
                ('recipient', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('delivery_memo', models.CharField(blank=True, max_length=255)),
                ('points_used', models.IntegerField(default=0)),
                ('payment', models.CharField(max_length=45)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='주문 완료', max_length=45)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
