# Generated by Django 4.2.1 on 2023-08-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Ingredient',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255, null=True)),
                ('tag', models.CharField(max_length=10, null=True)),
                ('answer', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Inquiry',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('사료', '사료'), ('간식', '간식')], max_length=10)),
                ('part', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('img', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_desc1', models.CharField(max_length=255)),
                ('category_desc2', models.CharField(max_length=255)),
                ('category_desc3', models.CharField(max_length=255)),
                ('stiffness', models.IntegerField()),
                ('size', models.IntegerField()),
                ('content1', models.CharField(max_length=255)),
                ('content2', models.CharField(max_length=255)),
                ('content_img1', models.CharField(max_length=255, null=True)),
                ('ingredient_img1', models.CharField(max_length=255, null=True)),
                ('ingredient_img2', models.CharField(max_length=255, null=True)),
                ('ingredient1', models.CharField(max_length=255)),
                ('ingredient2', models.CharField(max_length=255)),
                ('ship_method_img', models.CharField(max_length=255, null=True)),
                ('summary_info_img', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'ProductInfo',
            },
        ),
        migrations.CreateModel(
            name='ProductIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProductIngredients',
            },
        ),
        migrations.CreateModel(
            name='ProductNutrient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProductNutrient',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Recommendations',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('content', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
