# Generated by Django 4.2.1 on 2023-08-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Disease',
            },
        ),
        migrations.CreateModel(
            name='HealthAnomalies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.IntegerField()),
            ],
            options={
                'db_table': 'HealthAnomalies',
            },
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=255, null=True)),
                ('part', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'HealthReport',
            },
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Nutrients',
            },
        ),
        migrations.CreateModel(
            name='NutrientsHasDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_diary.disease')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_diary.nutrients')),
            ],
            options={
                'db_table': 'NutrientsHasDisease',
            },
        ),
    ]
