# Generated by Django 4.2.1 on 2023-08-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease_diary', '0001_initial'),
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.dog'),
        ),
        migrations.AddField(
            model_name='healthanomalies',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_diary.disease'),
        ),
        migrations.AddField(
            model_name='healthanomalies',
            name='health_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_diary.healthreport'),
        ),
    ]
